version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
      args:
        SENTRY_AUTH_TOKEN: "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"
    container_name: uschedule-frontend
    ports:
      - "3000:3000"
    networks:
      - uschedule-net
      - traefik
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`schedule.arsgreg.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

networks:
  traefik:
    external: true
  uschedule-net:
    name: uschedule-net
    driver: bridge
volumes:
  postgres-data:
