version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
      args:
        BUILD_ENV: build-${BUILD_ENV:-prod}
    container_name: uschedule-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.${BUILD_ENV:-prod}
    networks:
      - uschedule-net
      - traefik
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`schedule.arsgreg.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

networks:
  traefik:
    external: true
  uschedule-net:
    external: true
    name: uschedule-net
    driver: bridge
volumes:
  postgres-data:
